PYE24app/urls.py
from django.urls import path

from . import views

app_name = 'PYE24app'
urlpatterns = [
    # https://erasand.pythonanywhere.com/PYE/ZLMindex
    path("ZLMindex/", views.zlm_index, name="ZLMindex"),
    # https://erasand.pythonanywhere.com/PYE/ZLMdraws
    path("ZLMdraws/", views.zlm_draws, name="ZLMdraws"),
    # https://erasand.pythonanywhere.com/PYE/unique_id/ZLMgame
    path("<str:txUniqueId>/ZLMgame/", views.zlm_game, name="ZLMgame"),
    # https://erasand.pythonanywhere.com/PYE/unique_id/ZLMLsummary
    path("<str:txUniqueId>/ZLMsummary/", views.zlm_summary, name="ZLMsummary"),
]

PYE24app/models.py
from django.db import models


class zlm_Data(models.Model):
    '''
    ZLM Daten
    - Erstellungs-Datum
    - Letztes Bearbeitungs-Datum
    - Unique ID als Text
    - Vergangene Ziehungen als JSON (Dictionairy)
    - Ergebnisse zum Vergleichen als JSON (Dictionairy)
    '''
    created = models.DateTimeField()
    updated = models.DateTimeField()
    uniqueId = models.CharField(max_length=40)
    drawsData = models.JSONField()
    evalData = models.JSONField()

PYE24app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.utils import timezone
from .models import zlm_Data
from .zlm import zlm_Lotto
import pandas as pd
import uuid


def zlm_index(request):
    # Dictionairy für Template & Rendering
    context = {}
    return render(request, "PYE24app/ZLMindex.html", context)


def zlm_draws(request):
    # Unique ID erzeugen
    txUniqueId = str(uuid.uuid4())
    # Lotto Objekt
    obLotto = zlm_Lotto()
    # Leeres zlm_Data Objekt erzeugen & spechern
    obZlm = zlm_Data(
        created=timezone.now(),
        updated=timezone.now(),
        uniqueId=txUniqueId,
        drawsData=obLotto.dcBasicDraw,
        evalData=obLotto.dcEval
    )
    obZlm.save()
    # Dictionairy für Template & Rendering
    context = {
        # Unique ID
        "UNIQUE_ID": txUniqueId
    }
    return render(request, "PYE24app/ZLMdraws.html", context)


def zlm_game(request, txUniqueId):
    # Lotto Objekt
    obLotto = zlm_Lotto()
    # zlm_Data Objekt laden
    try:
        lsZlm = zlm_Data.objects.filter(uniqueId=txUniqueId)
        obZlm = lsZlm[0]
        blZlm = True
    except zlm_Data.DoesNotExist:
        blZlm = False
    # Prüfen, ob Ojekt gefunden wurde
    if blZlm:
        # Zufalls-Ziehungen übertragen
        obLotto.dcBasicDraw = obZlm.drawsData
        # Vergleich übertragen
        obLotto.dcEval = obZlm.evalData
        # Prüfen, ob dcBasicDraw vorhanden sind
        if not obLotto.dcBasicDraw:
            # Keine Grundlagen vorhanden, erstellen
            obLotto.mSetBasicDraws()
        # Grundlagen erweitern
        obLotto.mSetAdditionalDatas()
        # Logistische Regression
        obLotto.mSetLogRegression()
        # Zufalls-Tipp
        obLotto.mSetRandomReference()
        # Zufalls-Lotto Ziehung
        obLotto.mLottoDraw()
        # Ziehungen vergleichen
        obLotto.mEvalDraws()
        # Dictionairy für View erstellen
        obLotto.dcContext = {"UNIQUE_ID": txUniqueId}
        obLotto.mSetGameViewDict()
        # Ziehuung eintragen in Gurundlagen
        obLotto.mAddLottoDraw()
        # Modell speichern mit ergänzten Grundlagen und Vergleich
        obZlm.drawsData = obLotto.dcBasicDraw
        obZlm.evalData = obLotto.dcEval
        obZlm.updatet = timezone.now()
        obZlm.save()
    # Dictionairy für Template & Rendering
    return render(request, "PYE24app/ZLMgame.html", obLotto.dcContext)


def zlm_summary(request, txUniqueId):
    # Lotto Objekt
    obLotto = zlm_Lotto()
    # zlm_Data Objekt laden
    try:
        lsZlm = zlm_Data.objects.filter(uniqueId=txUniqueId)
        obZlm = lsZlm[0]
        blZlm = True
    except zlm_Data.DoesNotExist:
        blZlm = False
    # Prüfen, ob Ojekt gefunden wurde
    if blZlm:
        # Zufalls-Ziehungen übertragen
        obLotto.dcBasicDraw = obZlm.drawsData
        # Vergleich übertragen
        obLotto.dcEval = obZlm.evalData
        # Dictionairy für View erstellen
        obLotto.dcContext = {"UNIQUE_ID": txUniqueId}
        obLotto.mSetSummaryViewDict()
    # Dictionairy für Template & Rendering
    return render(request, "PYE24app/ZLMsummary.html", obLotto.dcContext)

PYE24app/templates/PYE24app/ZLMdraws.html
{% extends "ZLMbase.html" %}

{% block TITLE %}Grundlage{% endblock %}

{% block CONTENT %}
<div id="zufall" class="row py-2">
    <div class="col px-4">
        <h3>Zufalls-Ziehungen</h3>
        <p>Es werden 1'000 Zufalls-Ziehungen als Grundlage erstellt.</p>
    </div>
</div>
<div id="start" class="row py-2">
    <div class="col px-4">
        <a href="{% url 'PYE24app:ZLMgame' UNIQUE_ID %}" class="btn btn-primary btn-lg" tabindex="-1" role="button" aria-disabled="true">Fortfahren</a>
    </div>
</div>
<div id="back" class="row py-2">
    <div class="col px-4">
        <a href="{% url 'PYE24app:ZLMindex' %}" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true">Abbruch</a>
    </div>
</div>
{% endblock %}

PYE24app/templates/PYE24app/ZLMgame.html
{% extends "ZLMbase.html" %}

{% block TITLE %}Zufalls-Lotto{% endblock %}

{% block CONTENT %}
<div id="grundlage" class="row py-2">
    <div class="col px-4">
        <h3>Zufalls Ziehungen</h3>
        <p>als Grundlage</p>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col"><small>Datum / Zeit Ziehung</small></th>
                    <th scope="col">1. Zahl</th>
                    <th scope="col">2. Zahl</th>
                    <th scope="col">3. Zahl</th>
                    <th scope="col">4. Zahl</th>
                    <th scope="col">5. Zahl</th>
                    <th scope="col">6. Zahl</th>
                    <th scope="col">Zusatz-Zahl</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ R1_ID }}</td>
                    <td><small>{{ R1_DT }}</small></td>
                    <td>{{ R1_Z1 }}</td>
                    <td>{{ R1_Z2 }}</td>
                    <td>{{ R1_Z3 }}</td>
                    <td>{{ R1_Z4 }}</td>
                    <td>{{ R1_Z5 }}</td>
                    <td>{{ R1_Z6 }}</td>
                    <td>{{ R1_ZZ }}</td>
                </tr>
                <tr>
                    <td>{{ R2_ID }}</td>
                    <td><small>{{ R2_DT }}</small></td>
                    <td>{{ R2_Z1 }}</td>
                    <td>{{ R2_Z2 }}</td>
                    <td>{{ R2_Z3 }}</td>
                    <td>{{ R2_Z4 }}</td>
                    <td>{{ R2_Z5 }}</td>
                    <td>{{ R2_Z6 }}</td>
                    <td>{{ R2_ZZ }}</td>
                </tr>
                <tr>
                    <td colspan="9">...</td>
                </tr>
                <tr>
                    <td>{{ R3_ID }}</td>
                    <td><small>{{ R3_DT }}</small></td>
                    <td>{{ R3_Z1 }}</td>
                    <td>{{ R3_Z2 }}</td>
                    <td>{{ R3_Z3 }}</td>
                    <td>{{ R3_Z4 }}</td>
                    <td>{{ R3_Z5 }}</td>
                    <td>{{ R3_Z6 }}</td>
                    <td>{{ R3_ZZ }}</td>
                </tr>
                <tr>
                    <td>{{ R4_ID }}</td>
                    <td><small>{{ R4_DT }}</small></td>
                    <td>{{ R4_Z1 }}</td>
                    <td>{{ R4_Z2 }}</td>
                    <td>{{ R4_Z3 }}</td>
                    <td>{{ R4_Z4 }}</td>
                    <td>{{ R4_Z5 }}</td>
                    <td>{{ R4_Z6 }}</td>
                    <td>{{ R4_ZZ }}</td>
                </tr>
                <tr>
                    <td>{{ R5_ID }}</td>
                    <td><small>{{ R5_DT }}</small></td>
                    <td>{{ R5_Z1 }}</td>
                    <td>{{ R5_Z2 }}</td>
                    <td>{{ R5_Z3 }}</td>
                    <td>{{ R5_Z4 }}</td>
                    <td>{{ R5_Z5 }}</td>
                    <td>{{ R5_Z6 }}</td>
                    <td>{{ R5_ZZ }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="row py-2">
    <div class="col px-4">
        <br><hr><br>
    </div>
</div>
<div id="prognose" class="row py-2">
    <div class="col px-4">
        <h3>Prognose</h3>
        <p>für nächste Ziehung</p>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col"><small>Datum / Zeit Prognose</small></th>
                    <th scope="col">1. Zahl</th>
                    <th scope="col">2. Zahl</th>
                    <th scope="col">3. Zahl</th>
                    <th scope="col">4. Zahl</th>
                    <th scope="col">5. Zahl</th>
                    <th scope="col">6. Zahl</th>
                    <th scope="col">Zusatz-Zahl</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><small>{{ P_DT }}</small></td>
                    <td>{{ P_Z1 }}</td>
                    <td>{{ P_Z2 }}</td>
                    <td>{{ P_Z3 }}</td>
                    <td>{{ P_Z4 }}</td>
                    <td>{{ P_Z5 }}</td>
                    <td>{{ P_Z6 }}</td>
                    <td>{{ P_ZZ }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div id="zufall" class="row py-2">
    <div class="col px-4">
        <h3>Zufalls-Tipp</h3>
        <p>als Vergleich</p>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col"><small>Datum / Zeit Tipp</small></th>
                    <th scope="col">1. Zahl</th>
                    <th scope="col">2. Zahl</th>
                    <th scope="col">3. Zahl</th>
                    <th scope="col">4. Zahl</th>
                    <th scope="col">5. Zahl</th>
                    <th scope="col">6. Zahl</th>
                    <th scope="col">Zusatz-Zahl</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><small>{{ Z_DT }}</small></td>
                    <td>{{ Z_Z1 }}</td>
                    <td>{{ Z_Z2 }}</td>
                    <td>{{ Z_Z3 }}</td>
                    <td>{{ Z_Z4 }}</td>
                    <td>{{ Z_Z5 }}</td>
                    <td>{{ Z_Z6 }}</td>
                    <td>{{ Z_ZZ }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="row py-2">
    <div class="col px-4">
        <br><hr><br>
    </div>
</div>
<div id="ziehung" class="row py-2">
    <div class="col px-4">
        <h3>Lotto-Ziehung</h3>
        <p>aus Zufalls-Zahlen</p>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col"><small>Datum / Zeit Tipp</small></th>
                    <th scope="col">1. Zahl</th>
                    <th scope="col">2. Zahl</th>
                    <th scope="col">3. Zahl</th>
                    <th scope="col">4. Zahl</th>
                    <th scope="col">5. Zahl</th>
                    <th scope="col">6. Zahl</th>
                    <th scope="col">Zusatz-Zahl</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td><small>{{ L_DT }}</small></td>
                    <td>{{ L_Z1 }}</td>
                    <td>{{ L_Z2 }}</td>
                    <td>{{ L_Z3 }}</td>
                    <td>{{ L_Z4 }}</td>
                    <td>{{ L_Z5 }}</td>
                    <td>{{ L_Z6 }}</td>
                    <td>{{ L_ZZ }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="row py-2">
    <div class="col px-4">
        <br><hr><br>
    </div>
</div>
<div id="vergleich" class="row py-2">
    <div class="col px-4">
        <h3>Vergleich</h3>
    </div>
</div>
<div id="vergleich" class="row py-2">
    <div class="col-md-12 col-lg-6 px-4">
        <p><b>Richtige aus Prognose</b></p>
        <p>Zahlen: {{ V_P_Zs }}</p>
        <p>Zusatz-Zahl: {{ V_P_ZZ }}</p>
    </div>
    <div class="col-md-12 col-lg-6 px-4">
        <p><b>Richtige aus Zufalls-Tipp</b></p>
        <p>Zahlen: {{ V_Z_Zs }}</p>
        <p>Zusatz-Zahl: {{ V_Z_ZZ }}</p>
    </div>
</div>
<div id="start" class="row py-2">
    <div class="col px-4">
        <a href="{% url 'PYE24app:ZLMgame' UNIQUE_ID %}" class="btn btn-primary btn-lg" tabindex="-1" role="button" aria-disabled="true">Nächste Ziehung</a>
    </div>
</div>
<div id="back" class="row py-2">
    <div class="col px-4">
        <a href="{% url 'PYE24app:ZLMsummary' UNIQUE_ID %}" class="btn btn-primary btn-lg" tabindex="-1" role="button" aria-disabled="true">Fertig</a>
    </div>
</div>
{% endblock %}

PYE24app/templates/PYE24app/ZLMindex.html
{% extends "ZLMbase.html" %}

{% block TITLE %}Steckbrief{% endblock %}

{% block CONTENT %}
<div id="summary" class="row py-2">
    <div class="col-md-12 col-lg-6 px-4">
        <h3>Steckbrief :: Zusammenfassung</h3>
        <p>Ich habe das Maschinelle Lernen mit Python anhand von Lotto-Spielen ausprobiert.
           Die Prognosen waren eher bescheiden.
           Daraus entstand ZL::ML, eine Arbeit, die zeigt,
           wie Maschinelles Lernen und die Prognose von Lottozahlen mit dem Zufall zusammenhängen.</p>
    </div>
    <div class="col-md-12 col-lg-6 px-4">
        <h3>Steckbrief :: Technologie</h3>
        <p>Web-Applikation: Python, Pandas, Sklearn, Django-Framework</p>
    </div>
</div>
<div id="features" class="row py-2">
    <div class="col-md-12 col-lg-6 col-xl-4 px-4">
        <h3>Funktion :: Zufalls Lotto Spiel</h3>
        <p>6 Zahlen zwischen 1 und 49 - eine Zusatzzahl zwischen 1 und 12</p>
    </div>
    <div class="col-md-12 col-lg-6 col-xl-4 px-4">
        <h3>Funktionen :: Maschinelles Lernen</h3>
        <p>Logistische Regression zur Prognose der nächsten Ziehung<br>
           1000 Zufalls-Ziehungen und gleitende Durchschnitte als Grundlage<br>
           jede neue Zufalls-Ziehung wird den Grundlagen hinzugefügt</p>
    </div>
    <div class="col-md-12 col-lg-6 col-xl-4 px-4">
        <h3>Funktion :: Resultate</h3>
        <p>Prognose mit nächster Zufalls-Ziehung vergleichen<br>
           Zufalls-Tipp mit nächster Zufalls-Ziehung vergleichen<br>
           Mehrere Prognosen und Zufallsziehungen möglich<br>
           Zusammenfassung aller Ziehungen am Schluss</p>
    </div>
</div>
<div id="targets" class="row py-2">
    <div class="col-md-12 col-lg-6 col-xl-4 px-4">
        <h3>Ziel :: Maschinelles Lernen</h3>
        <p>Logistische Regression mit Python</p>
    </div>
    <div class="col-md-12 col-lg-6 col-xl-4 px-4">
        <h3>Ziel :: Algorithmische Automatisation</h3>
        <p>Vollständiger Ablauf ohne manuelle Eingaben</p>
    </div>
    <div class="col-md-12 col-lg-6 col-xl-4 px-4">
        <h3>Ziel :: Applikation</h3>
        <p>Interoperabel und im Web verfügbar</p>
    </div>
</div>
<div id="start" class="row py-2">
    <div class="col px-4">
        <a href="{% url 'PYE24app:ZLMdraws' %}" class="btn btn-primary btn-lg" tabindex="-1" role="button" aria-disabled="true">Spiel starten</a>
    </div>
</div>
<div id="back" class="row py-2">
    <div class="col px-4">
        <a href="https://www.erasand.ch/" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true">Zurück zu erasand.ch</a>
    </div>
</div>
{% endblock %}

PYE24app/templates/PYE24app/ZLMsummary.html
{% extends "ZLMbase.html" %}

{% block TITLE %}Zusammenfassung{% endblock %}

{% block CONTENT %}
<div id="summary" class="row py-2">
    <div class="col px-4">
        <h3>Zusammenfassung aller Ziehungen</h3>
        <p>Anzahl Ziehungen: {{ Anz_Drws }}</p>
    </div>
</div>
<div id="zahlen" class="row py-2">
    <div class="col-md-12 col-lg-6 px-4">
        <h3>Richtige aus Prognosen</h3>
        <p>Zahlen: {{ R_P_Zs }}<br>
           Durchschnitt: {{ D_P_Zs }}</p>
        <p>Zusatz-Zahl: {{ R_P_ZZ }}<br>
           Durchschnitt: {{ D_P_ZZ }}</p>
    </div>
    <div class="col-md-12 col-lg-6 px-4">
        <h3>Richtige aus Zufalls-Tipps</h3>
        <p>Zahlen: {{ R_Z_Zs }}<br>
           Durchschnitt: {{ D_Z_Zs }}</p>
        <p>Zusatz-Zahl: {{ R_Z_ZZ }}<br>
           Durchschnitt: {{ D_Z_ZZ }}</p>
    </div>
</div>
<div id="start" class="row py-2">
    <div class="col px-4">
        <a href="{% url 'PYE24app:ZLMdraws' %}" class="btn btn-primary btn-lg" tabindex="-1" role="button" aria-disabled="true">Spiel neu starten</a>
    </div>
</div>
<div id="back" class="row py-2">
    <div class="col px-4">
        <a href="https://www.erasand.ch/" class="btn btn-secondary btn-lg" tabindex="-1" role="button" aria-disabled="true">Zurück zu erasand.ch</a>
    </div>
</div>
{% endblock %}

PYE24app/templates/ZLMbase.html
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block TITLE %}TITLE{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    </head>
    <body>
        <div class="container-fluid text-center">
            <div id="title" class="row py-2">
                <div class="col px-4">
                    <h1>ZL::ML</h1>
                    <h4>Zufalls-Lotto :: Machinelles-Lernen</h4>
                </div>
            </div>
        </div>
        <div class="container-fluid text-center">
            {% block CONTENT %}CONTENT{% endblock %}
        </div>
        <div class="container-fluid text-center">
            <div id="footer" class="row py-2">
                <div class="col px-4">
                    <br><br>
                    <p>Andreas Ulrich - Artherstrasse 13 - 6300 Zug - andreas@erasand.ch - (c) März 2024 erasand.ch</p>
                </div>
            </div>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>